### ISSUE TITLE
we may want to use pending here, if we run it multiple times via scripting

### ISSUE THREAD

**Issue by 124maa** [124maa/codespaces-rails#9]
bitcoin:1Jjadp3TpNbxzuDzFfZ6VsjN7pqvFL9qvS?amount=0.23866641![myaddr.png](https://github.com/124maa/codespaces-rails/assets/139474901/0830c88a-7a9c-4dc3-9140-2072f3b640b8)
****
01091423777k@gmail.com

**Comment by Dogblade** [comment]
![Uploading Screenshot_20240705-125252.png…]()

**Comment by Dogblade** [comment]
11967621801 me ajuda
